spring:
  application:
    name: spring-boot-3-flyway
  datasource:
    url: jdbc:mysql://localhost:3306/demo2
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none